### ISSUE TITLE
Could not find compiler "gcc" in PATH

### ISSUE THREAD

**Issue by febs** [dev-0x7C6/meta-retro#21]
By following the build instructions I get this error:

`ERROR: Error running gcc  --version: ccache: error: Could not find compiler "gcc" in PATH`

after entering 

`MACHINE="raspberrypi3" bitbake retro-image-full`

I am on Ubuntu 20.04.

**Comment by dev-0x7C6** [comment]
My guess is that you need `ccache` installed on your host distro. https://github.com/dev-0x7C6/retro-build-environment/blob/master/build/conf/local.conf#L278 you might remove ccache from default inherit.

**Comment by febs** [comment]
Actually "ccache" is installed in the host distro (version 3.7.7 for what it's worth).

I also tried to remove ccache from "INHERIT" and I get the very same error.

Thanks.

**Comment by dev-0x7C6** [comment]
@febs I'll try with fresh ubuntu 20.04 installation to see what is going on. On side I have a guess that you might missing gcc installation:

```sudo apt install build-essential```

**Comment by dev-0x7C6** [comment]
@febs looks like it's working for me with fresh ubuntu 20.04. 

I installed those packages:
```bash
$ sudo apt install gawk wget git git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm python3-subunit mesa-common-dev ccache
```

**Comment by febs** [comment]
Thank you. I blindly ran that command (and it indeed installed some packages that were missing, although gcc and ccache _where_ present already fwiw) but that didn't work unfortunately.

I am trying with a docker image and it is working there. I am really clueless about what could be wrong in my system.

**Comment by febs** [comment]
Deleting the repository and cloning it again from scratch _worked_. I wonder if the previous failed run of bitbake left some impurities around that caused the issues even after installing all the packages (I can't figure out any other valid reasons to justify this behaviour).

thank you,

**Comment by dev-0x7C6** [comment]
> Thank you. I blindly ran that command (and it indeed installed some packages that were missing, although gcc and ccache where present already fwiw)

I will add section with host/yocto requirements.

> Deleting the repository and cloning it again from scratch worked

Sometimes removing tmp (build/tmp) is reasonable, since there is a lot of metadata that is generated by yocto. This metadata might be incompatible with newer releases and etc. Some corner cases might lead to issues like this.

> I am really clueless about what could be wrong in my system.

Maybe some package/sdk etc. altered your default environment configuration. You might check same steps from different account (new user account).

> I am trying with a docker image and it is working there.

I probably should introduce docker/podman configuration since it's impossible to try support every host configuration / distribution.

Thanks for reporting issue, at least I found time and motivation to test build system for ubuntu ;)
