### ISSUE TITLE
retroarch: linker error

### ISSUE THREAD

**Issue by MarkusVolk** [dev-0x7C6/meta-retro#6]
Hi,
i just tried to build your reference distribution for my rock pi. There were some minor issues but finally it built and is running awesome. Thanks for the great work. In a second step i switched from retro-image-minimal to retro-image-full to test if it still can be built and for some reason had a linker error in the retroarch build this time:

libHLSL.a(hlslParseables.cpp.o): undefined reference to symbol '_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc@@GLIBCXX_3.4.21'
libstdc++.so.6: error adding symbols: DSO missing from command line

I didn't have to search long for the reason. In retroarch Makefile line 2 is a switch for setting the linker to g++ that is disabled by default. Changing NEED_CXX_LINKER?=0 to NEED_CXX_LINKER?=1 did do the trick.

I thought about fixing this with a line 'EXTRA_OEMAKE += "NEED_CXX_LINKER=1"' in retroarch.inc. If that would be a proper solution for you i will send a pull request

Are you interested in supporting rockchip boards? If so i also could send a pull request to retro-build-environment. There are some minor drawbacks. Arms trusted-firmware-a refused to build with ccache enabled. Not sure why this is. Maybe because this is not c++ but baremetal. It wont build with gatesgarth but works with current poky master because  changes to the rock-pi devicetree are needed that require kernel 5.10 and therefore also a recent uboot source is needed. For the same reason there needs a patch to be merged into meta-rockchip. But i guess all of those issues will be fixed once the buildsystem gets ported to Hardknott.

I had two unbuildable cores but didn't have a closer look at the problem yet and only disabled them for now

**Comment by dev-0x7C6** [comment]
Hi,

> I thought about fixing this with a line 'EXTRA_OEMAKE += "NEED_CXX_LINKER=1"' in retroarch.inc. If that would be a proper solution for you i will send a pull request

I think this is proper way to fix that, I'll gladly accept PR.

> Are you interested in supporting rockchip boards?

I'm interested, it'll be awesome addition :-)

> Arms trusted-firmware-a refused to build with ccache enabled.

I think that can be workaround by putting `CCACHE_DISABLE_pn-trusted-firmware-a = "1"` in `local.conf`.

> But i guess all of those issues will be fixed once the buildsystem gets ported to Hardknott.

I think it's ok to switch to master branches.

Thanks,
Bartłomiej

**Comment by MarkusVolk** [comment]
CCACHE_DISABLE_pn-trusted-firmware-a = "1" fixed it :)

Won't have time to cleanup things tomorrow. But i'll send the PR within the next days

Thanks,
Markus

**Comment by MarkusVolk** [comment]
I updated retro-build-environment and did a clean build on it. 
Poky layers  commit sha  needed to be set a few days back, because latest changes broke meta-python2.
Looks like this it's nearly working out of the box now. One issue is left at do_image:

```
 * Problem 1/2:
 *   - conflicting requests
 *   - nothing provides mesa-vulkan-drivers needed by retroarch-1.9.0-git0+5e551dd92b-r0.cortexa72-cortexa53-crypto
 * 
 * Solution 1:
 *   - do not ask to install a package providing retroarch

 * Problem 2/2:
 *   - package retroarch-service-2.2-r0.cortexa72-cortexa53-crypto requires retroarch, but none of the providers can be installed
 *   - conflicting requests
 *   - nothing provides mesa-vulkan-drivers needed by retroarch-1.9.0-git0+5e551dd92b-r0.cortexa72-cortexa53-crypto
```
because DISTRO_FEATURE 'vulkan' is included by default and since rock-pi uses panfrost its not available. For now  i'm excluding the DISTRO_FEATURE from within custom.conf.

There are multiple warnings shown, mostly related to a new qa check [native-last]. Those are related to various layers. I sent a PR to meta-rauc that has already been merged, i also did fix some warnings inside your layers, will send PR for it.
Some more warnings were silenced by updating meta-openembedded and meta-intel. Now there should only be warnings coming from meta-qt5. The meta-qt5 yocto master branch has already fixed them, but they are still present in the vendor branch.

Thanks a lot,
Markus

**Comment by dev-0x7C6** [comment]
> Poky layers commit sha needed to be set a few days back, because latest changes broke meta-python2.

It's fine. Only thing that requires meta-python2 is now mame2016 and probably newer versions of it. Just wondering if this can be removed and updated to python3, I'll recheck situation here.

> For now i'm excluding the DISTRO_FEATURE from within custom.conf.

I think it's ok to exclude that in `local.conf` with proper override i.e. `DISTRO_FEATURES_remove_common-override-for-rockchip-family = "vulkan"`.
But I found that official meta-rockchip is not setting any default override (maybe it's setting this somewhere else?):
https://git.yoctoproject.org/cgit/cgit.cgi/meta-rockchip/tree/conf/machine/include/rockchip-defaults.inc
I found other meta-rockchip that is doing that here
https://github.com/rockchip-linux/meta-rockchip/blob/yocto-next/conf/machine/include/rockchip-common.inc#L14

Hint: current context overrides can be shown using `bitbake -e some-recipe | grep ^OVERRIDES`.

> There are multiple warnings shown, mostly related to a new qa check [native-last]. Those are related to various layers. I sent a PR to meta-rauc that has already been merged, i also did fix some warnings inside your layers, will send PR for it.
Some more warnings were silenced by updating meta-openembedded and meta-intel. Now there should only be warnings coming from meta-qt5. The meta-qt5 yocto master branch has already fixed them, but they are still present in the vendor branch.

I don't mind to left some warnings. Since everything can be fixed in meantime.

**Comment by dev-0x7C6** [comment]
I found that I'm already doing something like https://github.com/dev-0x7C6/retro-build-environment/commit/e6e3be8890fc8588beaec0c964071b837a271928 (space before `vulkan` keyword shouldn't be there, ups)

There is other way to disable `vulkan` for retroarch/cores since I introduced `libretro-vulkan-deps.bbclass` and with `VULKAN_AUTO_DEPENDS = "0"` it'll disable `vulkan` depends/rdepends for every package in `meta-retro`  that's using this class. But I'm unsure if this is good approach, I just feared that some custom drivers may use different packages, since `mesa-vulkan-drivers` sounds like mesa oriented only.

Thanks,
Bartłomiej

**Comment by MarkusVolk** [comment]
Rockchip-linux meta-layer unfortunately doesn't support mainline kernel, so its not usable. Due to your useful hint i encountered that there are machine overrides based on SOC_FAMILY

https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/conf/machine/include/soc-family.inc

At least there isn't an override needed for every single machine. I wonder if it could be done any nicer than this:

DISTRO_FEATURES_remove_rk3066 = "vulkan"
DISTRO_FEATURES_remove_rk3188 = "vulkan"
DISTRO_FEATURES_remove_rk3288 = "vulkan"
DISTRO_FEATURES_remove_rk3399 = "vulkan"

I woldn't worry to much about meta-python2. Since there are still big projects like chromium or qtwebengine relying on it, i bet it'll be still getting fixes

**Comment by dev-0x7C6** [comment]
> At least there isn't an override needed for every single machine. I wonder if it could be done any nicer than this:
> DISTRO_FEATURES_remove_rk3066 = "vulkan"
DISTRO_FEATURES_remove_rk3188 = "vulkan"
DISTRO_FEATURES_remove_rk3288 = "vulkan"
DISTRO_FEATURES_remove_rk3399 = "vulkan"

Maybe this? Could you check is this working for you?

```
OVERRIDES =. ${@bb.utils.contains_any('SOC_FAMILY', 'rk3066 rk3188 rk3288 rk3399', 'rockchip:', '', d)}
DISTRO_FEATURES_remove_rockchip = "vulkan"
```
Also this should work fine with meta-rockchip clone that I found. Since clone exporting rockchip directly (not sure if SOC_FAMILY is matching there, worst case is that rockchip override entry is added twice, but well).

> I wouldn't worry to much about meta-python2. Since there are still big projects like chromium or qtwebengine relying on it, i bet it'll be still getting fixes

For a moment situation was dicey, probably it'll receive new maintainer shortly.
https://lists.openembedded.org/g/openembedded-devel/message/87604
